//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocas.Domestic.Crm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ocaslr_applicationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Describes an application by an applicant within an application cycle.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ocaslr_application")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class ocaslr_application : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ocaslr_applicantid = "ocaslr_applicantid";
			public const string ocaslr_applicationcycleid = "ocaslr_applicationcycleid";
			public const string ocaslr_applicationId = "ocaslr_applicationid";
			public const string Id = "ocaslr_applicationid";
			public const string ocaslr_applicationnumber = "ocaslr_applicationnumber";
			public const string ocaslr_applicationstatusid = "ocaslr_applicationstatusid";
			public const string ocaslr_balance = "ocaslr_balance";
			public const string ocaslr_balance_Base = "ocaslr_balance_base";
			public const string ocaslr_basisforadmissionid = "ocaslr_basisforadmissionid";
			public const string ocaslr_basisforadmissionlock = "ocaslr_basisforadmissionlock";
			public const string ocaslr_completedsteps = "ocaslr_completedsteps";
			public const string ocaslr_currentid = "ocaslr_currentid";
			public const string ocaslr_currentlock = "ocaslr_currentlock";
			public const string ocaslr_effectivedate = "ocaslr_effectivedate";
			public const string Ocaslr_eventtrigger = "ocaslr_eventtrigger";
			public const string ocaslr_modifiedbyuser = "ocaslr_modifiedbyuser";
			public const string ocaslr_name = "ocaslr_name";
			public const string ocaslr_shoppingcartstatus = "ocaslr_shoppingcartstatus";
			public const string ocaslr_username = "ocaslr_username";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_ocaslr_application = "business_unit_ocaslr_application";
			public const string lk_ocaslr_application_createdby = "lk_ocaslr_application_createdby";
			public const string lk_ocaslr_application_createdonbehalfby = "lk_ocaslr_application_createdonbehalfby";
			public const string lk_ocaslr_application_modifiedby = "lk_ocaslr_application_modifiedby";
			public const string lk_ocaslr_application_modifiedonbehalfby = "lk_ocaslr_application_modifiedonbehalfby";
			public const string ocaslr_applicant_application = "ocaslr_applicant_application";
			public const string ocaslr_applicationcycle_application = "ocaslr_applicationcycle_application";
			public const string ocaslr_applicationstatus_application = "ocaslr_applicationstatus_application";
			public const string ocaslr_basisforadmission_ocaslr_applicati = "ocaslr_basisforadmission_ocaslr_applicati";
			public const string ocaslr_current_ocaslr_application = "ocaslr_current_ocaslr_application";
			public const string team_ocaslr_application = "team_ocaslr_application";
			public const string TransactionCurrency_ocaslr_application = "TransactionCurrency_ocaslr_application";
			public const string user_ocaslr_application = "user_ocaslr_application";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public ocaslr_application() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ocaslr_application";
		
		public const string EntitySchemaName = "ocaslr_application";
		
		public const string PrimaryIdAttribute = "ocaslr_applicationid";
		
		public const string PrimaryNameAttribute = "ocaslr_name";
		
		public const int EntityTypeCode = 10020;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Associates an application to an applicant contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicantid")]
		public Microsoft.Xrm.Sdk.EntityReference ocaslr_applicantid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ocaslr_applicantid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicantid");
				this.SetAttributeValue("ocaslr_applicantid", value);
				this.OnPropertyChanged("ocaslr_applicantid");
			}
		}
		
		/// <summary>
		/// Associates an application to an application cycle.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationcycleid")]
		public Microsoft.Xrm.Sdk.EntityReference ocaslr_applicationcycleid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ocaslr_applicationcycleid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationcycleid");
				this.SetAttributeValue("ocaslr_applicationcycleid", value);
				this.OnPropertyChanged("ocaslr_applicationcycleid");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationid")]
		public System.Nullable<System.Guid> ocaslr_applicationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ocaslr_applicationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationId");
				this.SetAttributeValue("ocaslr_applicationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ocaslr_applicationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.ocaslr_applicationId = value;
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationnumber")]
		public string ocaslr_applicationnumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ocaslr_applicationnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationnumber");
				this.SetAttributeValue("ocaslr_applicationnumber", value);
				this.OnPropertyChanged("ocaslr_applicationnumber");
			}
		}
		
		/// <summary>
		/// indicate the status of application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationstatusid")]
		public Microsoft.Xrm.Sdk.EntityReference ocaslr_applicationstatusid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ocaslr_applicationstatusid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationstatusid");
				this.SetAttributeValue("ocaslr_applicationstatusid", value);
				this.OnPropertyChanged("ocaslr_applicationstatusid");
			}
		}
		
		/// <summary>
		/// The balance owed to an applicant.  This balance is typically the result of a transfer from another application and can only be used by an OCAS employee.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_balance")]
		public Microsoft.Xrm.Sdk.Money ocaslr_balance
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ocaslr_balance");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_balance");
				this.SetAttributeValue("ocaslr_balance", value);
				this.OnPropertyChanged("ocaslr_balance");
			}
		}
		
		/// <summary>
		/// Value of the Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_balance_base")]
		public Microsoft.Xrm.Sdk.Money ocaslr_balance_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ocaslr_balance_base");
			}
		}
		
		/// <summary>
		/// Unique identifier for Basis for Admission associated with Application.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_basisforadmissionid")]
		public Microsoft.Xrm.Sdk.EntityReference ocaslr_basisforadmissionid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ocaslr_basisforadmissionid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_basisforadmissionid");
				this.SetAttributeValue("ocaslr_basisforadmissionid", value);
				this.OnPropertyChanged("ocaslr_basisforadmissionid");
			}
		}
		
		/// <summary>
		/// Value Indicating if there is a lock on the Basis For Admission of the Application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_basisforadmissionlock")]
		public System.Nullable<bool> ocaslr_basisforadmissionlock
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ocaslr_basisforadmissionlock");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_basisforadmissionlock");
				this.SetAttributeValue("ocaslr_basisforadmissionlock", value);
				this.OnPropertyChanged("ocaslr_basisforadmissionlock");
			}
		}
		
		/// <summary>
		/// The steps that have been completed on the application (Program Choice, Admission, International Credit Assessment, Transcript Requests, Payment)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_completedsteps")]
		public Microsoft.Xrm.Sdk.OptionSetValue ocaslr_completedsteps
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ocaslr_completedsteps");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_completedsteps");
				this.SetAttributeValue("ocaslr_completedsteps", value);
				this.OnPropertyChanged("ocaslr_completedsteps");
			}
		}
		
		/// <summary>
		/// Unique identifier for Current associated with Application.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_currentid")]
		public Microsoft.Xrm.Sdk.EntityReference ocaslr_currentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ocaslr_currentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_currentid");
				this.SetAttributeValue("ocaslr_currentid", value);
				this.OnPropertyChanged("ocaslr_currentid");
			}
		}
		
		/// <summary>
		/// Value Indicating of the Application is Locked
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_currentlock")]
		public System.Nullable<bool> ocaslr_currentlock
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ocaslr_currentlock");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_currentlock");
				this.SetAttributeValue("ocaslr_currentlock", value);
				this.OnPropertyChanged("ocaslr_currentlock");
			}
		}
		
		/// <summary>
		/// The date an application became active.  This date can be modified by OCAS for backdating purposes.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_effectivedate")]
		public System.Nullable<System.DateTime> ocaslr_effectivedate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ocaslr_effectivedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_effectivedate");
				this.SetAttributeValue("ocaslr_effectivedate", value);
				this.OnPropertyChanged("ocaslr_effectivedate");
			}
		}
		
		/// <summary>
		/// Field to act as a trigger for special events that need to be executed such as sending Declined Emails etc (Send Decline Email)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_eventtrigger")]
		public Microsoft.Xrm.Sdk.OptionSetValue Ocaslr_eventtrigger
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ocaslr_eventtrigger");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Ocaslr_eventtrigger");
				this.SetAttributeValue("ocaslr_eventtrigger", value);
				this.OnPropertyChanged("Ocaslr_eventtrigger");
			}
		}
		
		/// <summary>
		/// For auditing purposes,  CRM attribute that need to track which user inter, update or delete current entity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_modifiedbyuser")]
		public string ocaslr_modifiedbyuser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ocaslr_modifiedbyuser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_modifiedbyuser");
				this.SetAttributeValue("ocaslr_modifiedbyuser", value);
				this.OnPropertyChanged("ocaslr_modifiedbyuser");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_name")]
		public string ocaslr_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ocaslr_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_name");
				this.SetAttributeValue("ocaslr_name", value);
				this.OnPropertyChanged("ocaslr_name");
			}
		}
		
		/// <summary>
		/// The status of the shopping cart (Open, Checked out, Paid)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_shoppingcartstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue ocaslr_shoppingcartstatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ocaslr_shoppingcartstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_shoppingcartstatus");
				this.SetAttributeValue("ocaslr_shoppingcartstatus", value);
				this.OnPropertyChanged("ocaslr_shoppingcartstatus");
			}
		}
		
		/// <summary>
		/// For auditing purposes,  CRM attribute that need to track which user inter, update or delete current entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_username")]
		public string ocaslr_username
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ocaslr_username");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_username");
				this.SetAttributeValue("ocaslr_username", value);
				this.OnPropertyChanged("ocaslr_username");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Ocas.Domestic.Crm.Entities.ocaslr_applicationState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Ocas.Domestic.Crm.Entities.ocaslr_applicationState)(System.Enum.ToObject(typeof(Ocas.Domestic.Crm.Entities.ocaslr_applicationState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ActivityPointer> ocaslr_application_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ActivityPointer>("ocaslr_application_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_ActivityPointers");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ActivityPointer>("ocaslr_application_ActivityPointers", null, value);
				this.OnPropertyChanged("ocaslr_application_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Annotations")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Annotation> ocaslr_application_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Annotation>("ocaslr_application_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Annotations");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Annotation>("ocaslr_application_Annotations", null, value);
				this.OnPropertyChanged("ocaslr_application_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_applicantscholarship
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_applicantscholarship")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_applicantscholarship> ocaslr_application_applicantscholarship
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_applicantscholarship>("ocaslr_application_applicantscholarship", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_applicantscholarship");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_applicantscholarship>("ocaslr_application_applicantscholarship", null, value);
				this.OnPropertyChanged("ocaslr_application_applicantscholarship");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Appointments")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Appointment> ocaslr_application_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Appointment>("ocaslr_application_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Appointments");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Appointment>("ocaslr_application_Appointments", null, value);
				this.OnPropertyChanged("ocaslr_application_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.AsyncOperation> ocaslr_application_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.AsyncOperation>("ocaslr_application_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_AsyncOperations");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.AsyncOperation>("ocaslr_application_AsyncOperations", null, value);
				this.OnPropertyChanged("ocaslr_application_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.BulkDeleteFailure> ocaslr_application_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.BulkDeleteFailure>("ocaslr_application_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_BulkDeleteFailures");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.BulkDeleteFailure>("ocaslr_application_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("ocaslr_application_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_custom_audit
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_custom_audit")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.custom_audit> ocaslr_application_custom_audit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.custom_audit>("ocaslr_application_custom_audit", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_custom_audit");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.custom_audit>("ocaslr_application_custom_audit", null, value);
				this.OnPropertyChanged("ocaslr_application_custom_audit");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.DuplicateRecord> ocaslr_application_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.DuplicateRecord>("ocaslr_application_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_DuplicateBaseRecord");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.DuplicateRecord>("ocaslr_application_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("ocaslr_application_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.DuplicateRecord> ocaslr_application_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.DuplicateRecord>("ocaslr_application_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_DuplicateMatchingRecord");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.DuplicateRecord>("ocaslr_application_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("ocaslr_application_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Emails")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Email> ocaslr_application_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Email>("ocaslr_application_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Emails");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Email>("ocaslr_application_Emails", null, value);
				this.OnPropertyChanged("ocaslr_application_Emails");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Faxes")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Fax> ocaslr_application_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Fax>("ocaslr_application_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Faxes");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Fax>("ocaslr_application_Faxes", null, value);
				this.OnPropertyChanged("ocaslr_application_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_financialtransaction
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_financialtransaction")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_financialtransaction> ocaslr_application_financialtransaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_financialtransaction>("ocaslr_application_financialtransaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_financialtransaction");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_financialtransaction>("ocaslr_application_financialtransaction", null, value);
				this.OnPropertyChanged("ocaslr_application_financialtransaction");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Letters")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Letter> ocaslr_application_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Letter>("ocaslr_application_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Letters");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Letter>("ocaslr_application_Letters", null, value);
				this.OnPropertyChanged("ocaslr_application_Letters");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_offer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_offer")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_offer> ocaslr_application_offer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_offer>("ocaslr_application_offer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_offer");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_offer>("ocaslr_application_offer", null, value);
				this.OnPropertyChanged("ocaslr_application_offer");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_opportunityproduct
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_opportunityproduct")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.OpportunityProduct> ocaslr_application_opportunityproduct
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.OpportunityProduct>("ocaslr_application_opportunityproduct", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_opportunityproduct");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.OpportunityProduct>("ocaslr_application_opportunityproduct", null, value);
				this.OnPropertyChanged("ocaslr_application_opportunityproduct");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_order
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_order")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.SalesOrder> ocaslr_application_order
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrder>("ocaslr_application_order", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_order");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrder>("ocaslr_application_order", null, value);
				this.OnPropertyChanged("ocaslr_application_order");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_orderitem
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_orderitem")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.SalesOrderDetail> ocaslr_application_orderitem
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrderDetail>("ocaslr_application_orderitem", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_orderitem");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrderDetail>("ocaslr_application_orderitem", null, value);
				this.OnPropertyChanged("ocaslr_application_orderitem");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.PhoneCall> ocaslr_application_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.PhoneCall>("ocaslr_application_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_PhoneCalls");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.PhoneCall>("ocaslr_application_PhoneCalls", null, value);
				this.OnPropertyChanged("ocaslr_application_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.PrincipalObjectAttributeAccess> ocaslr_application_PrincipalObjectAttributeAccesses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.PrincipalObjectAttributeAccess>("ocaslr_application_PrincipalObjectAttributeAccesses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.PrincipalObjectAttributeAccess>("ocaslr_application_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("ocaslr_application_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_ProcessSession")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ProcessSession> ocaslr_application_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ProcessSession>("ocaslr_application_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_ProcessSession");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ProcessSession>("ocaslr_application_ProcessSession", null, value);
				this.OnPropertyChanged("ocaslr_application_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_programchoice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_programchoice")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_programchoice> ocaslr_application_programchoice
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_programchoice>("ocaslr_application_programchoice", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_programchoice");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_programchoice>("ocaslr_application_programchoice", null, value);
				this.OnPropertyChanged("ocaslr_application_programchoice");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.RecurringAppointmentMaster> ocaslr_application_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.RecurringAppointmentMaster>("ocaslr_application_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_RecurringAppointmentMasters");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.RecurringAppointmentMaster>("ocaslr_application_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("ocaslr_application_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ServiceAppointment> ocaslr_application_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ServiceAppointment>("ocaslr_application_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_ServiceAppointments");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ServiceAppointment>("ocaslr_application_ServiceAppointments", null, value);
				this.OnPropertyChanged("ocaslr_application_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_shoppingcart
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_shoppingcart")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Opportunity> ocaslr_application_shoppingcart
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Opportunity>("ocaslr_application_shoppingcart", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_shoppingcart");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Opportunity>("ocaslr_application_shoppingcart", null, value);
				this.OnPropertyChanged("ocaslr_application_shoppingcart");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_SocialActivities")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.SocialActivity> ocaslr_application_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.SocialActivity>("ocaslr_application_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_SocialActivities");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.SocialActivity>("ocaslr_application_SocialActivities", null, value);
				this.OnPropertyChanged("ocaslr_application_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_Tasks")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Task> ocaslr_application_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Task>("ocaslr_application_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_Tasks");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Task>("ocaslr_application_Tasks", null, value);
				this.OnPropertyChanged("ocaslr_application_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_transcriptrequest
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_transcriptrequest")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_transcriptrequest> ocaslr_application_transcriptrequest
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_transcriptrequest>("ocaslr_application_transcriptrequest", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_transcriptrequest");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_transcriptrequest>("ocaslr_application_transcriptrequest", null, value);
				this.OnPropertyChanged("ocaslr_application_transcriptrequest");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_application_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_application_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.UserEntityInstanceData> ocaslr_application_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.UserEntityInstanceData>("ocaslr_application_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_application_UserEntityInstanceDatas");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.UserEntityInstanceData>("ocaslr_application_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("ocaslr_application_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_ocaslr_application_ocaslr_documentdistrib
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_ocaslr_application_ocaslr_documentdistrib")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.Ocaslr_documentdistributionrecord> ocaslr_ocaslr_application_ocaslr_documentdistrib
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.Ocaslr_documentdistributionrecord>("ocaslr_ocaslr_application_ocaslr_documentdistrib", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_ocaslr_application_ocaslr_documentdistrib");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.Ocaslr_documentdistributionrecord>("ocaslr_ocaslr_application_ocaslr_documentdistrib", null, value);
				this.OnPropertyChanged("ocaslr_ocaslr_application_ocaslr_documentdistrib");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_ocaslr_application_ocaslr_voucher_Application
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_ocaslr_application_ocaslr_voucher_Application")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.ocaslr_voucher> ocaslr_ocaslr_application_ocaslr_voucher_Application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_voucher>("ocaslr_ocaslr_application_ocaslr_voucher_Application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_ocaslr_application_ocaslr_voucher_Application");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.ocaslr_voucher>("ocaslr_ocaslr_application_ocaslr_voucher_Application", null, value);
				this.OnPropertyChanged("ocaslr_ocaslr_application_ocaslr_voucher_Application");
			}
		}
		
		/// <summary>
		/// 1:N ocaslr_transfer_application_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_transfer_application_salesorderdetail")]
		public System.Collections.Generic.IEnumerable<Ocas.Domestic.Crm.Entities.SalesOrderDetail> ocaslr_transfer_application_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrderDetail>("ocaslr_transfer_application_salesorderdetail", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_transfer_application_salesorderdetail");
				this.SetRelatedEntities<Ocas.Domestic.Crm.Entities.SalesOrderDetail>("ocaslr_transfer_application_salesorderdetail", null, value);
				this.OnPropertyChanged("ocaslr_transfer_application_salesorderdetail");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_ocaslr_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_ocaslr_application")]
		public Ocas.Domestic.Crm.Entities.BusinessUnit business_unit_ocaslr_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.BusinessUnit>("business_unit_ocaslr_application", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ocaslr_application_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ocaslr_application_createdby")]
		public Ocas.Domestic.Crm.Entities.SystemUser lk_ocaslr_application_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ocaslr_application_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ocaslr_application_createdonbehalfby")]
		public Ocas.Domestic.Crm.Entities.SystemUser lk_ocaslr_application_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_ocaslr_application_createdonbehalfby");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_ocaslr_application_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_ocaslr_application_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ocaslr_application_modifiedby")]
		public Ocas.Domestic.Crm.Entities.SystemUser lk_ocaslr_application_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ocaslr_application_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ocaslr_application_modifiedonbehalfby")]
		public Ocas.Domestic.Crm.Entities.SystemUser lk_ocaslr_application_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_ocaslr_application_modifiedonbehalfby");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("lk_ocaslr_application_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_ocaslr_application_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 ocaslr_applicant_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicantid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_applicant_application")]
		public Ocas.Domestic.Crm.Entities.Contact ocaslr_applicant_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.Contact>("ocaslr_applicant_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicant_application");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.Contact>("ocaslr_applicant_application", null, value);
				this.OnPropertyChanged("ocaslr_applicant_application");
			}
		}
		
		/// <summary>
		/// N:1 ocaslr_applicationcycle_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationcycleid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_applicationcycle_application")]
		public Ocas.Domestic.Crm.Entities.ocaslr_applicationcycle ocaslr_applicationcycle_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_applicationcycle>("ocaslr_applicationcycle_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationcycle_application");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_applicationcycle>("ocaslr_applicationcycle_application", null, value);
				this.OnPropertyChanged("ocaslr_applicationcycle_application");
			}
		}
		
		/// <summary>
		/// N:1 ocaslr_applicationstatus_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_applicationstatusid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_applicationstatus_application")]
		public Ocas.Domestic.Crm.Entities.Ocaslr_applicationstatus ocaslr_applicationstatus_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.Ocaslr_applicationstatus>("ocaslr_applicationstatus_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_applicationstatus_application");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.Ocaslr_applicationstatus>("ocaslr_applicationstatus_application", null, value);
				this.OnPropertyChanged("ocaslr_applicationstatus_application");
			}
		}
		
		/// <summary>
		/// N:1 ocaslr_basisforadmission_ocaslr_applicati
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_basisforadmissionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_basisforadmission_ocaslr_applicati")]
		public Ocas.Domestic.Crm.Entities.ocaslr_basisforadmission ocaslr_basisforadmission_ocaslr_applicati
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_basisforadmission>("ocaslr_basisforadmission_ocaslr_applicati", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_basisforadmission_ocaslr_applicati");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_basisforadmission>("ocaslr_basisforadmission_ocaslr_applicati", null, value);
				this.OnPropertyChanged("ocaslr_basisforadmission_ocaslr_applicati");
			}
		}
		
		/// <summary>
		/// N:1 ocaslr_current_ocaslr_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_currentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ocaslr_current_ocaslr_application")]
		public Ocas.Domestic.Crm.Entities.ocaslr_current ocaslr_current_ocaslr_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_current>("ocaslr_current_ocaslr_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ocaslr_current_ocaslr_application");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.ocaslr_current>("ocaslr_current_ocaslr_application", null, value);
				this.OnPropertyChanged("ocaslr_current_ocaslr_application");
			}
		}
		
		/// <summary>
		/// N:1 team_ocaslr_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_ocaslr_application")]
		public Ocas.Domestic.Crm.Entities.Team team_ocaslr_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.Team>("team_ocaslr_application", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_ocaslr_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_ocaslr_application")]
		public Ocas.Domestic.Crm.Entities.TransactionCurrency TransactionCurrency_ocaslr_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.TransactionCurrency>("TransactionCurrency_ocaslr_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_ocaslr_application");
				this.SetRelatedEntity<Ocas.Domestic.Crm.Entities.TransactionCurrency>("TransactionCurrency_ocaslr_application", null, value);
				this.OnPropertyChanged("TransactionCurrency_ocaslr_application");
			}
		}
		
		/// <summary>
		/// N:1 user_ocaslr_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_ocaslr_application")]
		public Ocas.Domestic.Crm.Entities.SystemUser user_ocaslr_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Ocas.Domestic.Crm.Entities.SystemUser>("user_ocaslr_application", null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_completedsteps")]
		public virtual ocaslr_application_ocaslr_completedsteps? ocaslr_completedstepsEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ocaslr_application_ocaslr_completedsteps?)(EntityOptionSetEnum.GetEnum(this, "ocaslr_completedsteps")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				ocaslr_completedsteps = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_eventtrigger")]
		public virtual ocaslr_application_Ocaslr_eventtrigger? Ocaslr_eventtriggerEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ocaslr_application_Ocaslr_eventtrigger?)(EntityOptionSetEnum.GetEnum(this, "ocaslr_eventtrigger")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				Ocaslr_eventtrigger = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ocaslr_shoppingcartstatus")]
		public virtual ocaslr_application_ocaslr_shoppingcartstatus? ocaslr_shoppingcartstatusEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ocaslr_application_ocaslr_shoppingcartstatus?)(EntityOptionSetEnum.GetEnum(this, "ocaslr_shoppingcartstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				ocaslr_shoppingcartstatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ocaslr_application_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((ocaslr_application_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}